### ISSUE TITLE
Standup 10:10 am Tuesday

### ISSUE THREAD

**Issue by emilyb7** [foundersandcoders/goals-app#14]
@amgoforth we've scheduled a morning standup for tomorrow at 10:10. Noga (UI / UX designer) will be joining us. If you're free and _would like_ to, you're welcome to join (via Google hangouts or whatever). If you're not free, we can alternatively schedule a catchup at a time that suits you. Just let us know!

**Comment by amgoforth** [comment]
@emilyb7 I'm free! I can do a hangout; let me know the details. Looking forward to it.

**Comment by amgoforth** [comment]
@emilyb7 my hangout email address is alexmgoforth@gmail.com.
